### ISSUE TITLE
array to woocommerce

### ISSUE THREAD

**Issue by eros2187** [woocommerce/wc-api-php#124]
I'm using this library to use it in a mobile application
I wanted to know how you can let me return a json array like this:

**Object {products: Array (2), http: Object}**

And not as I currently receive
**(2) [Object, Object]
(2) [Object, Object]**

This and my code:

`<?php>

require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

	$url =$_POST ['url'];
	$consumer_key=	$_POST ['consumer_key'];
	$consumer_secret=$_POST ['consumer_secret'];

$woocommerce = new Client($url, $consumer_key, $consumer_secret,[
        'wp_api' => true,
        'version' => 'wc/v1',
    ]);
 
   echo json_encode ($woocommerce->get('products')); 
   echo json_encode ($woocommerce->get('products',$parameters = ['category' => $id])); 

 ?>
`
How can I fix it? thank you

**Comment by claudiosanches** [comment]
Depends on the REST API version, since the new WooCommerce integration with the WordPress REST API does not return `{products: Array (2), http: Object}` anymore. And you should use this new integration since the legacy API will be removed soon: https://github.com/woocommerce/woocommerce/wiki/Contributing-to-the-WooCommerce-REST-API#deprecation-of-older-versions
