### ISSUE TITLE
How can i manage the cart from api 

### ISSUE THREAD

**Issue by redsparkers** [woocommerce/wc-api-php#211]
Hello,
how can i manage the cart from api. 
hope for solution

**Comment by gthayer** [comment]
I do not believe there is anything like this currently, but I'd love to see the ability to get cart totals through the API. Feed in product IDs, get back shipping and taxes.

I'm working on a 3rd party app which includes a checkout and integrates with Woo. I'd love the option of letting Woo do all the math instead of basically re-building shipping rules for each client.

**Comment by claudiosanches** [comment]
This doesn't sound like a question related to this REST API library.
For questions about the WooCommerce REST API use https://wordpress.org/support/plugin/woocommerce
