### ISSUE TITLE
have syntax error

### ISSUE THREAD

**Issue by vahidalvandi** [woocommerce/wc-api-php#220]
i use php 7 and before connect got error

     // Test if return a valid JSON.
        if (JSON_ERROR_NONE !== json_last_error()) {
            $message = function_exists('json_last_error_msg') ? json_last_error_msg() : 'Invalid JSON returned';
            throw new HttpClientException($message, $this->response->getCode(), $this->request, $this->response);
        }

**Comment by yedincisenol** [comment]
@vahidalvandi i have same problem. If you remove this line (https://github.com/woocommerce/wc-api-php/blob/master/src/WooCommerce/HttpClient/HttpClient.php#L206) or remove Client::version with "/" character, may will work. In my case cause is .net 

`WASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT` bug. Server solition: https://support.plesk.com/hc/en-us/articles/115001674173-Bots-cannot-access-web-server-403-Forbidden

**Comment by vahidalvandi** [comment]
thanks. i use directadmin

**Comment by thiagomarini** [comment]
Same problem, I'm using PHP 7.2 and getting `Syntax error` when listing orders.

**Comment by claudiosanches** [comment]
I'm improving this output in the new version, but `Syntax error` means that is an invalid JSON syntax, probably your website or your server showing something else that is not a valid JSON response, like Thiago pointed out a problem with a page moved permanently.

Closing since is not an issue with this library, sounds like you need to fix your server.

**Comment by claudiosanches** [comment]
Also in the case of redirects, you can use the `follow_redirects` option in this library.
