### ISSUE TITLE
Can't authenticate using JWT

### ISSUE THREAD

**Issue by Jordan4jc** [woocommerce/wc-api-php#225]
It would seem through the Docs that I should be able to use any other method of authentication that the WP Rest Api supports.

So I'm familar with JWT authentication and decided to go with that. After getting it setup and adding the necessary changes to my .htaccess as far as I can tell, I grabbed an authentication token and attempted to pass it in the `Authorization` header as `Bearer ***` and I'm still getting an error

```
{
    "code": "woocommerce_rest_cannot_view",
    "message": "Sorry, you cannot list resources.",
    "data": {
        "status": 403
    }
}
```

When I tried to list orders at `wp-json/wc/v2/orders`

Do I still have to go through the process of setting up keys if I'm trying to use this JWT authentication? Or is there some other configuration I need to do with WC in order to enable this type of Authentication?

**Comment by claudiosanches** [comment]
> It would seem through the Docs that I should be able to use any other method of authentication that the WP Rest Api supports.

Using the WooCommerce REST API, yes, you can use any authentication method.

If you are going to use this library, you need to extend it and write new code to support JWT authentication, there is no code on this library for it right now, and since is a 3rd party plugin for authentication, you should write your code.
