### ISSUE TITLE
Getting customer by email is not documented

### ISSUE THREAD

**Issue by drghirlanda** [woocommerce/wc-api-php#238]
Hi! Thanks a lot for this PHP API! The docs mention that it is possible to look up a customer by email (rather than by id), but I could not find an example. I have tried a few things based on a post on stackoverflow, such as:

    $wc->get( 'customers', [ email => 'customer@gmail.com' ] )

but I get an empty array as a return. I am sure the email is correct. It would be great to add to the docs how to do this.

(Some background: I am using the Subscription Gifting and I trigger a webhook when a new subscription is created, and the email of the giftee is included in the payload, but not the username. I would like to retrieve the username based on the email.)

Thanks!

**Comment by claudiosanches** [comment]
I tried to reproduce and works just fine. If returned empty is because could find any user. I'll guess that is search with the incorrect role, since by default WooCommerce REST API uses `customer`, this will works for you (since you have sure that have the email belongs to an user on your WordPress installation):

```php
$wc->get( 'customers', [ 'email' => 'customer@gmail.com', 'role' => 'all' ] );
```
