### ISSUE TITLE
POSTMAN "Invalid JSON body passed.",  "status": 400,

### ISSUE THREAD

**Issue by janevskidamjan** [woocommerce/wc-api-php#239]
Trying to log in to get the token in postman
http://localhost:8000//wp-json/jwt-auth/v1/token
In the body i put:
{
	"username": "Admin"
	"password": "password22"
}

And i get this :
{
    "code": "rest_invalid_json",
    "message": "Invalid JSON body passed.",
    "data": {
        "status": 400,
        "json_error_code": 4,
        "json_error_message": "Syntax error"
    }
}

**Comment by claudiosanches** [comment]
This should not work because this library excepts that you are using the authentication methods built in WooCommerce.

**Comment by igitur** [comment]
@claudiosanches Hope you don't mind that I chip in here. Are you saying that the steps outlined in https://github.com/XiaoFaye/WooCommerce.NET#usage-wordpress-rest-api---oauthjwt-authentication (to enable JWT auth) are not worth it, because WooCommerce doesn't support those methods explicitly? I can't imagine why the author of WooCommerce.NET would have implemented the JWT auth in the client then.

**Comment by claudiosanches** [comment]
@igitur by default our official libraries only support authentication methods already on WooCommerce, not sure why the author of WooCommerce.NET choice to use a 3rd party authentication method.
For now we will support WooCommerce authentication methods until WordPress core doesn't include any method by default.
