### ISSUE TITLE
how can i delete metadata?

### ISSUE THREAD

**Issue by e-hop** [woocommerce/wc-api-php#295]
this function [wc_delete_order_item_meta ](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-order-item-functions.php) deletes the metadata but how can i accomplish it with this package

**Comment by claudiosanches** [comment]
Hello @e-hop,

For questions about WooCommerce's REST API, please use the support forum: https://wordpress.org/support/plugin/woocommerce/
Also you can consult the REST API documentation in: https://woocommerce.github.io/woocommerce-rest-api-docs/

I'm closing this issue for now since isn't related to this PHP library.
